// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vacopqvxiqtuaygukpjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhY29wcXZ4aXF0dWF5Z3VrcGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NTY2NzEsImV4cCI6MjA1NTQzMjY3MX0.6X7wcD6yg-YFn7B3nXHyL4Jzv2KZXJYcfIfSpvfddZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);